# Generated by Django 3.1.5 on 2021-02-11 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemeFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('caption', models.CharField(max_length=250)),
                ('image_url', models.URLField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_file', models.ImageField(blank=True, default=None, upload_to='feedback_pics')),
            ],
        ),
    ]
